#!/usr/bin/env bash
# Generate docs/DESIGN_INDEX.md from design doc frontmatter.
#
# Usage: bash scripts/generate-design-index.sh
#
# Extracts YAML frontmatter from all docs/design/**/*.md and produces
# a compact markdown table for AI session context injection.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
DESIGN_DIR="$REPO_ROOT/docs/design"
OUTPUT="$REPO_ROOT/docs/DESIGN_INDEX.md"

if [[ ! -d "$DESIGN_DIR" ]]; then
  echo "No design docs directory at $DESIGN_DIR — skipping"
  exit 0
fi

# Extract a frontmatter field value from between --- markers
get_field() {
  local file="$1" key="$2"
  sed -n '/^---$/,/^---$/p' "$file" | grep "^${key}:" | head -1 | sed "s/^${key}:[[:space:]]*//" | sed 's/^"//;s/"$//' | tr -d '\r' || true
}

# Extract services array: [a, b] → "a, b"
get_services() {
  local file="$1"
  sed -n '/^---$/,/^---$/p' "$file" | grep '^services:' | head -1 | sed 's/.*\[//;s/\].*//' | tr -d '"' | tr -d '\r' || true
}

# Status emoji lookup
emoji_for() {
  case "$1" in
    current)             echo "✅" ;;
    partially-outdated)  echo "⚠️" ;;
    superseded)          echo "🚫" ;;
    draft)               echo "📝" ;;
    not-implemented)     echo "🔲" ;;
    *)                   echo "❓" ;;
  esac
}

# Collect all design docs
ENTRIES=""
COUNT=0
MISSING=0

while IFS= read -r filepath; do
  number=$(get_field "$filepath" "number")
  if [[ -z "$number" ]]; then
    MISSING=$((MISSING + 1))
    echo "WARNING: missing frontmatter: ${filepath#"$REPO_ROOT"/}" >&2
    continue
  fi

  status=$(get_field "$filepath" "status")
  description=$(get_field "$filepath" "description")
  title=$(get_field "$filepath" "title")
  superseded_by=$(get_field "$filepath" "superseded_by")
  services=$(get_services "$filepath")

  desc="${description:-$title}"
  [[ -n "$superseded_by" ]] && desc="$desc → $superseded_by"
  emoji=$(emoji_for "$status")

  ENTRIES="${ENTRIES}| ${number} | ${emoji} | ${services} | ${desc} |
"
  COUNT=$((COUNT + 1))
done < <(find "$DESIGN_DIR" -name '*.md' -type f | sort)

if [[ $COUNT -eq 0 ]]; then
  echo "No design docs with frontmatter found — skipping"
  exit 0
fi

# Generate the index
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
# Design Document Index

> Auto-generated by \`scripts/generate-design-index.sh\`. Do not edit manually.
> Re-generate: \`bash scripts/generate-design-index.sh\`

| # | St | Services | Description |
|---|---|----------|-------------|
${ENTRIES}
**Legend:** ✅ current · ⚠️ partially-outdated · 🚫 superseded · 📝 draft · 🔲 not-implemented
EOF

echo "Generated $OUTPUT with $COUNT entries"
[[ $MISSING -gt 0 ]] && echo "WARNING: $MISSING doc(s) missing frontmatter (not included)"
